services:
  backend:
    container_name: ria-backend-container
    image: ria-backend
    build: ./backend
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - django-static:/usr/src/app/staticfiles
      - ./backend/db.sqlite3:/usr/src/app/db.sqlite3
      - ./backend/media:/usr/src/app/media
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 -w 1
  frontend:
    container_name: ria-frontend-container
    image: ria-frontend
    build: ./frontend
    volumes:
      - react-build:/usr/src/app/build
    depends_on:
      - backend
  nginx:
    container_name: ria-nginx-container
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - django-static:/usr/src/app/staticfiles
      - react-build:/usr/share/nginx/html
      - ./backend/media:/usr/src/app/media
      - ./http-server/nginx:/etc/nginx/conf.d
      - ./http-server/certbot/conf:/etc/letsencrypt
      - ./http-server/certbot/www:/var/www/certbot
    depends_on:
      - frontend
  certbot:
    container_name: ria-certbot-container
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./http-server/certbot/conf:/etc/letsencrypt
      - ./http-server/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  django-static:
  react-build:
  media: