services:
  backend:
    container_name: ria-backend-container
    image: ria-backend
    build: ./backend
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - django-static:/usr/src/app/staticfiles
      - media:/usr/src/app/media
      - ./backend/db.sqlite3:/usr/src/app/db.sqlite3
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 -w 1
  frontend:
    container_name: ria-frontend-container
    image: ria-frontend
    build: ./frontend
    restart: unless-stopped
    expose:
      - 3000
    command: serve -s /usr/src/app/build -l 3000
    depends_on:
      - backend
  nginx:
    container_name: ria-nginx-container
    image: ria-nginx
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - django-static:/usr/src/app/staticfiles
      - media:/usr/src/app/media
    depends_on:
      - frontend

volumes:
  django-static:
  media: