services:
  backend:
    container_name: ria-backend-container
    image: ria-backend
    build: ./backend
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - django-static:/usr/src/app/staticfiles
      - ./backend/db.sqlite3:/usr/src/app/db.sqlite3
      - ./backend/media:/usr/src/app/media
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 -w 1
  frontend:
    container_name: ria-frontend-container
    image: ria-frontend
    build: ./frontend
    volumes:
      - react-build:/usr/src/app/build
    depends_on:
      - backend
  nginx:
    container_name: ria-nginx-container
    image: ria-nginx
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - django-static:/usr/src/app/staticfiles
      - react-build:/usr/share/nginx/html
      - ./backend/media:/usr/src/app/media
    depends_on:
      - frontend

volumes:
  django-static:
  react-build:
  media: