# Generated by Django 3.2.12 on 2023-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.PositiveIntegerField(verbose_name='Cтаж работы'),
        ),
    ]
