# Generated by Django 3.2.12 on 2023-04-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('icon', models.CharField(choices=[('bi bi-facebook', 'Facebook'), ('bi bi-instagram', 'Instagram'), ('bi bi-twitter', 'Twitter'), ('bi bi-whatsapp', 'WhatsApp'), ('bi bi-telegram', 'Telegram'), ('bi bi-telephone-fill', 'Телефон'), ('bi bi-geo-alt-fill', 'Карта')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(help_text='Формат ввода: +7 (999) 999-99-99', max_length=18)),
            ],
            options={
                'verbose_name_plural': 'Номера телефонов',
            },
        ),
    ]
