# Generated by Django 3.2.12 on 2023-04-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_links_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(choices=[('bi bi-facebook', 'Facebook'), ('bi bi-instagram', 'Instagram'), ('bi bi-twitter', 'Twitter'), ('bi bi-whatsapp', 'WhatsApp'), ('bi bi-telegram', 'Telegram'), ('bi bi-youtube', 'YouTube'), ('bi bi-geo-alt-fill', 'Map')], max_length=50),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(help_text='Формат ввода: +7 (999) 999-99-99', max_length=18, verbose_name='Телефон'),
        ),
    ]
