# Generated by Django 3.2.12 on 2023-04-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20230418_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(choices=[('bi bi-facebook', 'Facebook'), ('bi bi-instagram', 'Instagram'), ('bi bi-twitter', 'Twitter'), ('bi bi-whatsapp', 'WhatsApp'), ('bi bi-telegram', 'Telegram'), ('bi bi-youtube', 'YouTube'), ('bi bi-geo-alt-fill', 'Map')], max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(help_text='Формат ввода: +7 (999) 999-99-99', max_length=18, unique=True, verbose_name='Номер'),
        ),
    ]
