# Generated by Django 3.2.12 on 2023-04-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('photo', models.ImageField(upload_to='news/', verbose_name='Фото')),
                ('preview_text', models.TextField(blank=True, null=True, verbose_name='Текст для предпросмотра')),
                ('main_text', models.TextField(verbose_name='Основой текст')),
            ],
        ),
    ]
