# Generated by Django 3.2.12 on 2023-04-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20230421_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularplace',
            options={'verbose_name': 'Популярное место', 'verbose_name_plural': 'Популярные места'},
        ),
        migrations.AlterField(
            model_name='popularplace',
            name='photo',
            field=models.ImageField(upload_to='places/', verbose_name='Фото'),
        ),
    ]
